# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 19
Metrics/AbcSize:
  Max: 50

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 281

# Offense count: 6
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 33
Style/Documentation:
  Enabled: false

# Offense count: 4
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'
    - 'spec/models/version_spec.rb'
    - 'test/dummy/app/models/person.rb'
